#!/usr/bin/env bash
# Install nginx on you web-01 server

sudo apt-get -y update
sudo apt-get -y install nginx

# listen on port 80
sudo ufw allow 'Nginx HTTP'

sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo service nginx start
